version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: nginx-1.13-alpine
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.5"
  php:
    container_name: php-7.1-fpm
    build:
      context: .
      dockerfile: "./docker-image-builds/php-7.1/Dockerfile"
    volumes:
      - ./src:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
    working_dir: /application
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.6"
  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
      # By default logging in mysql is disabled. I see no need to enable myself
      #- ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.7"


networks:
  static-network:
    ipam:
      config:
        - subnet: "${IPADDRESS}.0/28"
