version: '3'

services:
  nginx:
    image: nginx:${NGINXVERSION}-alpine
    container_name: nginx-${NGINXVERSION}-alpine-${PROJECTNAME}
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    working_dir: /var/www/html
    depends_on:
    depends_on:
      - php
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.5"
  php:
    container_name: php-${PHPVERSION}-fpm-${PROJECTNAME}
    build:
          context: ./docker-image-builds/php
          dockerfile: Dockerfile
          args:
            PHPVERSION: ${PHPVERSION}
    volumes:
      - ./src:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
      #- ./conf/php-fpm.conf:/etc
    working_dir: /application
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.6"
  db:
    image: mysql:${MYSQLVERSION}
    container_name: mysql-${NGINXVERSION}-${PROJECTNAME}
    volumes:
      - ./db:/var/lib/mysql
      #- ./conf/mysql.cnf:/etc/mysql/
      # By default logging in mysql is disabled. I see no need to enable myself
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=${PROJECTNAME}
      - MYSQL_USER=${PROJECTNAME}
      - MYSQL_PASSWORD=123
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.7"

networks:
  static-network:
    ipam:
      config:
        - subnet: "${IPV4ADDRESS}.0/28"
