version: '3.6'

services:
  apache:
    container_name: "${PROJECTNAME}-apache-${APACHEVERSION}"
    image: "httpd:${APACHEVERSION}-alpine"
    links:
      - "phpfpm"
    volumes:
      - ./${PROJECTNAME}/${WWWROOT}:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    hostname: "docker.com"
    environment:
      - FASTCGI=fcgi://phpfpm:9000
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.5"
  nginx:
    container_name: "${PROJECTNAME}-nginx-${NGINXVERSION}"
    image: "nginx:${NGINXVERSION}"
    working_dir: "/var/www/html/"
    volumes:
      - ./${PROJECTNAME}/${WWWROOT}:/var/www/html/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.8"
  phpfpm:
    container_name: "${PROJECTNAME}-phpfpm-${PHPVERSION}"
    build:
      context: ./dockerfiles/php
      dockerfile: Dockerfile
      args:
        PHPVERSION: ${PHPVERSION}
    volumes:
      - ./${PROJECTNAME}/${WWWROOT}:/var/www/html/
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
      - ./ssh-agent:/.ssh-agent
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.6"
  mysql:
    container_name: "${PROJECTNAME}-mysql-${MYSQLVERSION}"
    image: "mysql:${MYSQLVERSION}"
    volumes:
      - ./mysql-${MYSQLVERSION}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTPASS}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    networks:
      static-network:
        ipv4_address: "${IPV4ADDRESS}.7"
  sshagent:
    container_name: "${PROJECTNAME}-sshagent"
    user: "1000"
    build:
      context: ./dockerfiles/ssh-agent
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/.ssh
      - ./ssh-agent:/.ssh-agent
networks:
  static-network:
    ipam:
      config:
        - subnet: "${IPV4ADDRESS}.0/28"
