version: '3.6'

services:
  apache:
    container_name: "${PROJECTNAME}-apache-${APACHEVERSION}"
    image: "httpd:${APACHEVERSION}-alpine"
    volumes:
      - "${PROJECTROOT}/${WWWROOT}:/usr/local/apache2/htdocs/"
      - "./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf"
      - "./conf/server.key:/usr/local/apache2/conf/server.key"
      - "./conf/server.crt:/usr/local/apache2/conf/server.crt"
    hostname: "docker.com"
    environment:
      - "FASTCGI=fcgi://phpfpm:9000"
    networks:
      nameless-static-network:
        ipv4_address: "${IPV4ADDRESS}.5"
#  nginx:
#    container_name: "${PROJECTNAME}-nginx-${NGINXVERSION}"
#    image: "nginx:${NGINXVERSION}"
#    working_dir: "/var/www/html/"
#    volumes:
#      - "${PROJECTROOT}/${WWWROOT}:/var/www/html/"
#      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
#    networks:
#      nameless-static-network:
#        ipv4_address: "${IPV4ADDRESS}.8"
  phpfpm:
    container_name: "${PROJECTNAME}-phpfpm-${PHPVERSION}"
    build:
      context: "./dockerfiles/php"
      dockerfile: "Dockerfile"
      args:
        PHPVERSION: "${PHPVERSION}"
    user: "${USERID}"
    volumes:
      - "${PROJECTROOT}/${WWWROOT}:/var/www/html/"
      - "./conf/php.ini:/usr/local/etc/php/php.ini"
    networks:
      nameless-static-network:
        ipv4_address: "${IPV4ADDRESS}.6"
#  mysql:
#    container_name: "${PROJECTNAME}-mysql-${MYSQLVERSION}"
#    image: "mysql:${MYSQLVERSION}"
#    volumes:
#      - "./mysql-${MYSQLVERSION}:/var/lib/mysql"
#    environment:
#      - "MYSQL_ROOT_PASSWORD=${ROOTPASS}"
#      - "MYSQL_DATABASE=${DBNAME}"
#      - "MYSQL_USER=${DBUSER}"
#      - "MYSQL_PASSWORD=${DBPASS}"
#    networks:
#      nameless-static-network:
#        ipv4_address: "${IPV4ADDRESS}.7"
networks:
  nameless-static-network:
    name: "${PROJECTNAME}-static-network"
    ipam:
      config:
        - subnet: "${IPV4ADDRESS}.0/28"
