version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: nginx-1.13-alpine
    ports: 
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php
    networks:
      - dev.network
  php:
    container_name: php-7.1-fpm
    build:
      context: .
      dockerfile: "./docker-image-builds/php7.1/Dockerfile"
    volumes:
      - ./www:/var/www
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
    working_dir: /var/www
    networks:
      - dev.network

networks:
    dev.network:
